services:
  dev:
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    volumes:
        - ./:/workspace
        - lingma:/root/.lingma
        - cache:/root/.cache
        - ./scripts/entrypoint.sh:/entrypoint
        - docker:/var/lib/docker
    stdin_open: true
    tty: true
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  lingma:
  docker:
  cache: